/*
 * Copyright (C) 2020 Frank Hoogeveen
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package nl.fh.group_calculators;

import java.util.logging.Level;
import java.util.logging.Logger;
import nl.fh.calculator.Calculator;
import nl.fh.calculator.EvaluationException;
import nl.fh.group.Group;
import nl.fh.homomorphism.GroupHomomorphism;
import nl.fh.homomorphism.HomomorphismException;

/**
 * Given a calculator that gives Set<Element> as output. This embedder
 * calculates a group homomorphism that embeds the group generated by the set
 * in the overall group. 
 * 
 * 
 * @author frank
 */
public class EmbeddingCalculator implements Calculator<Group> {

    private final GroupProperty property;

    /**
     * 
     * @param property should evaluate to a subgroup of Group group
     */
    public EmbeddingCalculator(GroupProperty property) {
        this.property = property;
    }

    @Override
    public GroupHomomorphism evaluate(Group group) throws EvaluationException {

        // retrieve the subgroup to be embedded
        Group subgroup = (Group) group.getProperty(property);
        
        try {
            return group.embed(subgroup);
        } catch (HomomorphismException ex) {
            String mess = "cannot calculate embedding";
            Logger.getLogger(EmbeddingCalculator.class.getName()).log(Level.SEVERE, mess, ex);
            throw new EvaluationException(mess);
        }
    }
}
